### ISSUE TITLE
This doesn't work for me at all

### ISSUE THREAD

**Issue by ghost** [BareConductive/midi-piano#1]
I get no sound and I admit I don't know enough about midi to play with the parameters to see where I am failing. Could you please help me?

**Comment by stefandz** [comment]
Hi there

Did you already try the tutorial [here](http://www.bareconductive.com/make/on-board-midi-mode/)? If you follow that step-by-step all should work fine.

If you have any further problems, feel free to reply here or email us at info@bareconductive.com.

Many thanks

Stefan

**Comment by ghost** [comment]
Oh, right. I missed the hardware soldering bit. Interesting. Many thanks for pointing this out to me. May I ask why the connections are not soldered together by default? Does this change any other functionalities of the board?

**Comment by stefandz** [comment]
Glad this worked out for you. The solder blobs take the VS1053 chip out of MP3 playback mode and put it into MIDI playback mode. If you want to go back and follow an MP3 playback example you will need to remove the two solder blobs you made in the tutorial. I realise this isn't made clear in the MIDI keyboard example tutorial and we'll get that rectified soon.
