### ISSUE TITLE
Is it possible to create two instruments on the one board?

### ISSUE THREAD

**Issue by mannakelly** [BareConductive/midi-piano#2]
I am trying to create four independent instruments but I only have two boards. Is it possible to partition the input pins to activate two instruments from the sound bank on the one board?

**Comment by loosepascal** [comment]
This is indeed possible. One way to do this is to call the `setupMidi` function twice. For example, what you can do is have 
~~~~
if(i < 6) {
  setupMidi1();
}
if (6 <= i) {
  setupMidi2();
}
~~~~
right at start of the `if(MPR121.isNewTouch(i))` function. You need to create `setupMidi1();` and `setupMidi2();`, where you create the two new instruments.

**Comment by mannakelly** [comment]
Thanks for the reply, I get an error message "setupMidi1" was not declared in this scope. Maybe  I dont have it placed in the right area.
<img width="693" alt="screen shot 2018-04-16 at 13 01 13" src="https://user-images.githubusercontent.com/38377384/38807991-6c85b2fa-4176-11e8-921e-80823d1d0056.png">

`

**Comment by loosepascal** [comment]
Indeed, you need to create `setupMidi1()` and `setupMidi2()`. You can use the `setupMidi()` function that we wrote as part of the example, and just copy paste that to create the two additional setupMidi functions.

**Comment by mannakelly** [comment]
I've tried putting that code and variations of it in various places and I either get all notes being played at once on 2 electrodes or an error message of midiSetup(); not declared in scope

**Comment by mannakelly** [comment]
[midi-pianodual-public 2.zip](https://github.com/BareConductive/midi-piano/files/1922075/midi-pianodual-public.2.zip)

**Comment by mannakelly** [comment]
https://github.com/mannakelly/midi-pianodual-public

This is some code that I wrote that solves the problem. 
It doesn't use the setupMidi(); or setupMidi1();.
